from reportlab.lib import colors
from reportlab.lib.pagesizes import A4
from reportlab.platypus import SimpleDocTemplate, Paragraph, Spacer, Image, Table, TableStyle
from reportlab.lib.styles import getSampleStyleSheet, ParagraphStyle
from reportlab.lib.units import inch
from datetime import datetime
import os

def generate_report(patient_data, scan_results, output_path, original_img_path=None, heatmap_img_path=None):
    """
    Generates a PDF report for a patient's scan.
    """
    doc = SimpleDocTemplate(output_path, pagesize=A4)
    styles = getSampleStyleSheet()
    story = []

    # --- Header ---
    title_style = ParagraphStyle(
        'Title',
        parent=styles['Heading1'],
        fontSize=24,
        textColor=colors.HexColor('#0056b3'),
        spaceAfter=12,
        alignment=1 # Center
    )
    story.append(Paragraph("PancreScan AI Report", title_style))
    story.append(Paragraph(f"Date: {datetime.now().strftime('%Y-%m-%d %H:%M')}", styles['Normal']))
    story.append(Spacer(1, 12))
    story.append(Paragraph("<b>CONFIDENTIAL MEDICAL REPORT</b>", styles['Normal']))
    story.append(Spacer(1, 24))

    # --- Patient Information ---
    story.append(Paragraph("Patient Information", styles['Heading2']))
    patient_info = [
        ["Patient Name:", patient_data['name']],
        ["MRN:", patient_data['mrn']],
        ["Age:", str(patient_data['age'])],
        ["Gender:", patient_data['gender']],
    ]
    t_patient = Table(patient_info, colWidths=[2*inch, 4*inch])
    t_patient.setStyle(TableStyle([
        ('FONTNAME', (0,0), (0,-1), 'Helvetica-Bold'),
        ('BACKGROUND', (0,0), (0,-1), colors.whitesmoke),
        ('GRID', (0,0), (-1,-1), 0.5, colors.lightgrey),
        ('ALIGN', (0,0), (-1,-1), 'LEFT'),
        ('PADDING', (0,0), (-1,-1), 6),
    ]))
    story.append(t_patient)
    story.append(Spacer(1, 24))

    # --- Clinical Findings ---
    story.append(Paragraph("Clinical Findings", styles['Heading2']))
    
    # Diagnosis Logic
    prediction = scan_results['prediction']
    confidence = scan_results['confidence']
    is_tumor = "Tumor" in prediction or "Malignant" in prediction
    
    color = colors.red if is_tumor else colors.green
    diagnosis_style = ParagraphStyle(
        'Diagnosis',
        parent=styles['Normal'],
        fontSize=14,
        textColor=color,
        spaceAfter=12
    )
    
    story.append(Paragraph(f"<b>Prediction:</b> {prediction}", diagnosis_style))
    story.append(Paragraph(f"<b>Confidence:</b> {confidence:.2%}", styles['Normal']))
    story.append(Paragraph(f"<b>Model Used:</b> {scan_results['model']}", styles['Normal']))
    story.append(Spacer(1, 12))

    # --- Visual Evidence ---
    story.append(Paragraph("Visual Evidence", styles['Heading2']))
    
    images_row = []
    if original_img_path and os.path.exists(original_img_path):
        img1 = Image(original_img_path, width=3*inch, height=3*inch)
        images_row.append(img1)
    
    if heatmap_img_path and os.path.exists(heatmap_img_path):
        img2 = Image(heatmap_img_path, width=3*inch, height=3*inch)
        images_row.append(img2)
        
    if images_row:
        t_images = Table([images_row], colWidths=[3.5*inch]*len(images_row))
        t_images.setStyle(TableStyle([
            ('ALIGN', (0,0), (-1,-1), 'CENTER'),
            ('VALIGN', (0,0), (-1,-1), 'TOP'),
        ]))
        story.append(t_images)
        story.append(Paragraph("Left: Original Scan | Right: AI Saliency Map (Red areas indicate regions of interest)", styles['Italic']))

    story.append(Spacer(1, 24))

    # --- Disclaimer ---
    story.append(Paragraph("Disclaimer", styles['Heading3']))
    disclaimer_text = """
    This report was generated by an Artificial Intelligence system (PancreScan) and is intended for assistance only. 
    It does NOT constitute a final medical diagnosis. All findings must be verified by a qualified radiologist or medical professional. 
    The AI model may have limitations and can produce false positives or false negatives.
    """
    story.append(Paragraph(disclaimer_text, styles['Normal']))

    # Build PDF
    doc.build(story)
    return output_path
